### ISSUE TITLE
Control tainting when throwing exception

### ISSUE THREAD

**Issue by miguelvelezmj25** [gmu-swe/phosphor#102]
Hello Professor,

I wanted to check if the tainting that I am seeing in the following example is correct. I am using control-flow tracking, but not the controlTrackExceptions options:

```
boolean a = MultiTainter.taintedBoolean(false, "a");

if (A) {
    throw new RuntimeException();
}

boolean b = false // a's taint gets propagated into b
```

If I check the taint of ```b```, it is has ```"a"```. That seems correct since the assignment depends on whether the program throws the exception depending on ```A```.  Is this tainting correct? If so, what does the option controlTrackExceptions do? Based on the description "Enable taint tracking through exceptional control flow", I would guess that if I do not enable the option, ```b``` should not be tainted.

Thanks.

**Comment by jon-bell** [comment]
`controlTrackExceptions` is a bit of a misnomer - it should be more along the lines of `interproceduralControlTrackExceptions`. In the example above, `b` gets `A`'s taint without the setting of `controlTrackExceptions` because of the normal post dominator analysis that we do: control flow never returns from `if(A)` to the rest of the method, so we say that if you don't take it, we should propagate the tag throughout the method. It will behave exactly the same with:

```
boolean a = MultiTainter.taintedBoolean(false, "a");

if (A) {
    return;
}

boolean b = false // a's taint gets propagated into b
```

Setting the option will make this be an interprocedural dynamic analysis.

**Comment by miguelvelezmj25** [comment]
I see. Thank you!
