### ISSUE TITLE
More problems with reflection and primitive arrays

### ISSUE THREAD

**Issue by chhokrad** [gmu-swe/phosphor#55]
```java
public class rough_work {

	public static class MyStruct_arr {
		public int[] arr_i = { 1, 2, 3 };
	}

	public static void main(String[] args) throws Exception {

		MyStruct_arr m = new MyStruct_arr();
		MultiTainter.taintedObject(m, new Taint<String>("tainted_dierctly"));
		MultiTainter.taintedIntArray(m.arr_i, "tainted_directly");

		System.out.println(MultiTainter.getTaint(m.arr_i[0]));
		System.out.println(MultiTainter.getTaint(m.arr_i[1]));
		System.out.println(MultiTainter.getTaint(m.arr_i[2]));

		for (Field f : m.getClass().getDeclaredFields()) {
			if (f.getType().isArray()) {
				int[] temp = (int[]) f.get(m);
				for (int i = 0; i < Array.getLength(temp); i++)
					System.out.println(MultiTainter.getTaint(temp[i]));
			}
		}
	}

// Output

>Taint [lbl=tainted_directly  deps = []]
>Taint [lbl=tainted_directly  deps = []]
>Taint [lbl=tainted_directly  deps = []]
>null
>null
>null

```

**Comment by jon-bell** [comment]
No, that's a bug. 

Please do this:
Take all of the issues like this that you are finding. Add unit tests for them, just like the ones that I showed you. Comment on this issues as you find new issues. I will then look at them all at once. You are also more than welcome to attach a debugger and see what the issues is and submit a PR to fix it. Most of these issues are caused by regressions from performance optimizations that I added in the past 6-7 months: the original (OOPSLA artifact) version of Phosphor allocated a shadow array for every primitive array, now it doesn't, which greatly reduces overhead, but also left some lurking bugs throughout.

**Comment by chhokrad** [comment]
Thanks for your reply, as of now I have no issues tainting objects by reflection. But I am experiencing problems retrieving taints through reflections. I'll add more issues to this chain soon.
